name: Openplant Automation Protocols
description: Repository for Openplant Automation Protocols and Tutorials
author: Felipe Xavier Buson
baseurl: /
url: https://openplant.github.io/openplant_automation_protocols
